.travis.yml, package.json, scripts/ci/travis-script.sh
Add files for travis webhook for our CI/CD pipeline.
=> chore(): add travis

build.conf.js, scripts/version-placeholders.js, src/lib/package.json
Add @ngx-translate/core as peerDep since thats what we use for i18n in the platform.
=> chore(): add ngx-translate as peerDep

angular.json, karma.conf.js, package.json, src/lib/system/system.service.spec.ts, src/lib/test.ts, src/lib/tsconfig.spec.json
Add initial unit test for VantageSystemService.
=> feat(system): initial unit test

scripts/build-release, src/lib/_theming.scss, src/theme.scss
Distribute theming and typography overrides (without font) so the field and our internal products can reuse them for both light and dark mode
=> feat(theming): add vantage theming file to package

src/lib/_theming.scss
Adding styles for compact toolbar buttons, and leading icon buttons. Excluding icon buttons
=> feat: style for compact toolbar buttons

package-lock.json
Make sure the pipeline passes without `npm audit` issues.
=> fix(): fix all audit problems

src/docs-ui/app/app.module.ts, src/docs-ui/app/app.routes.ts, src/lib/access/access.module.ts, src/lib/access/guards/block-root-access.guard.ts, src/lib/access/guards/block-user-access.guard.ts, src/lib/access/index.ts, src/lib/access/package.json, src/lib/access/public_api.ts, src/lib/auth/guards/authentication.guard.ts
Make `VantageAuthenticationGuard` chainable via guards
Create `VantageBlockRootAccessGuard` and `VantageBlockUserAccessGuard` to check for `admin` flag on user and block/allow access into a route.
=> feat(): add access module with initial guards

package-lock.json, src/lib/testing/cypress/cypress.ts
- Optimize login to reduce unnecessary visits which waste a lot of time. 
- Also ensure it works on Electron.
=> fix(cypress): allow login to work in electron and reduce visits

src/lib/app/apps.service.ts
Add `favorite` to apps service
- Added `favorite` as optional parameter to IApp interface
=> feat(update-app-service): add favorite

src/lib/testing/cypress/README.md, src/lib/testing/cypress/cypress.ts
add whitelist sso cookies utility
=> feat(cypress): add whitelist sso cookies utility

src/lib/testing/cypress/README.md, src/lib/testing/cypress/cypress.ts
feat(testing-cypress): add wait for angular func
=> feat(testing-cypress): add wait for angular func

scripts/build-release, src/lib/utilities/pre-loader/README.md
Was creating a nested directory. 😞 
See: https://github.com/Teradata/vantage-ui-platform-nightly/tree/master/utilities/pre-loader/pre-loader
=> build(pre-loader): fix copy command

src/lib/app/apps.service.ts, src/lib/app/tags.service.ts, src/lib/public_api.ts, src/lib/sqle/connection.service.ts, src/lib/sqle/dictionary.service.ts, src/lib/sqle/index.ts, src/lib/sqle/package.json, src/lib/sqle/public_api.ts, src/lib/sqle/query.service.ts, src/lib/sqle/sqle.module.ts, src/lib/system/system.service.ts
Test steps
- `npm run build:lib`
- `npm pack ./deploy/ui-platform/`
- Go into another repo 😉  and update the package json to `@td-vantage/ui-platform": "file:../vantage-ui-platform/td-vantage-ui-platform-1.0.0-beta.0.tgz", `(Change path if necessary)
- `npm i` within this new repo
- Pull in module and verify services work as expected
=> feat(sqle): add sqle package

scripts/build-release, src/docs-ui/app/app.module.ts, src/docs-ui/app/main/main.component.ts, src/lib/public_api.ts, src/lib/theme/index.ts, src/lib/theme/public_api.ts, src/lib/theme/theme.module.ts, src/lib/theme/theme.service.ts, src/lib/utilities/public_api.ts
- npm run build:lib
- npm pack
- pull in another project and test
Thoughts on all those files in that theme dir?
=> feat(theme): create a theme package

src/lib/theme/package.json
feat(theme): actually create a package
=> feat(theme): actually create a package

src/lib/theme/_overrides.scss, src/lib/utilities/pre-loader/pre-loader.scss
feat(pre-loader): use proper background color
=> feat(pre-loader): use proper background color

src/lib/app/app.module.ts, src/lib/app/app.service.spec.ts, src/lib/app/app.service.ts, src/lib/app/public_api.ts
Rename `VantageAppsService` into `VantageAppService`
=> refactor(): rename apps service to app service

src/docs-ui/app/main/main.component.ts, src/lib/auth/guards/authentication.guard.ts, src/lib/auth/session/session.service.ts, src/lib/index.ts, src/lib/public_api.ts, src/lib/sqle/query.service.ts, src/lib/testing/cypress/public_api.ts, src/lib/testing/index.ts, src/lib/testing/public_api.ts, src/lib/theme/_overrides.scss, src/lib/tsconfig.lib.json, src/lib/utilities/pre-loader/index.ts, src/lib/utilities/pre-loader/pre-loader.html, src/lib/utilities/pre-loader/pre-loader.scss, src/lib/utilities/pre-loader/pre-loader.ts, src/lib/utilities/public_api.ts, src/lib/utilities/user-feedback/index.ts, src/lib/utilities/user-feedback/public_api.ts
- Hooks into pre-loader within guard to also show pre-loader while authentication is being checked.
- Address https://github.com/Teradata/vantage-ui-platform/pull/42/files#r373169497
- Fixes https://github.com/Teradata/vantage-ui-platform/issues/39
- BREAKING CHANGE: Removes IUser from Session service that was duplicated in the User service.
=> feat(pre-loader): hook into pre-loader within guard

src/lib/app/app.service.ts
=> fix(app-service): add `app_state` to service

src/lib/sqle/connection.service.ts
- Return observable from connect method
- Remove timeout and retry operators since that should probably be done by the consumer
=> feat(connection-service): cleanup connect method

src/lib/sqle/query.service.ts
Use `TdHttpService` so that the `VantageAuthenticationInterceptor`  can properly intercept the responses.
=> fix(query-service): use tdhttp service

src/lib/theme/_overrides.scss, src/lib/theme/_palette.scss
Adding all background classes in the design system
=> feat: adding bgc classes

src/lib/theme/_mixins.scss
=> fix: mixing bug

src/lib/theme/_overrides.scss
.tc had reversed the right color for dark and light mode
=> fix(styling): wrong text color

src/docs-ui/app/app.module.ts, src/docs-ui/app/demos/demos.component.html, src/docs-ui/app/demos/demos.component.ts, src/lib/sqle/credentials-dialog/credentials-dialog.component.html, src/lib/sqle/credentials-dialog/credentials-dialog.component.scss, src/lib/sqle/credentials-dialog/credentials-dialog.component.spec.ts, src/lib/sqle/credentials-dialog/credentials-dialog.component.ts, src/lib/sqle/index.ts, src/lib/sqle/package.json, src/lib/sqle/sqle.module.ts
Add credentials dialog for reusability and standardization with lots of improvements.
=> feat(sqle): add credentials dialog

src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.scss
Quick styling adjustment for the explore more icon
=> feat(app-switcher): adjusting css styling

src/lib/utilities/pre-loader/pre-loader.html
Removes tooltip that appears on hover.
=> fix(pre-loader): remove hover title tooltip

src/lib/theme/_overrides.scss
Quick small fix for big issue :) regarding bgc classes not having a background.
=> fix: bgc classes

package-lock.json, package.json, src/assets/i18n/en.json, src/docs-ui/app/app.component.html, src/docs-ui/app/app.module.ts, src/lib/user-profile/index.ts, src/lib/user-profile/package.json, src/lib/user-profile/public_api.ts, src/lib/user-profile/user-profile.component.html, src/lib/user-profile/user-profile.component.ts, src/lib/user-profile/user-profile.module.ts
Component that wraps the covalent user-profile component. Has the theme service and session service baked in.
~Waiting on https://github.com/Teradata/covalent/pull/1770~
=> feat(vui-user-profile): add component

src/lib/sqle/query.service.ts
Expose new payload property to allow numeric values to be returned as strings.
=> feat(num-vals-as-str): result set numeric values as strings

src/lib/sqle/query.service.ts
Defined new interface to type column metadata info.
=> feat(nums-as-strings): define interface for column metadata

src/lib/theme/_overrides.scss
Body color in editor filter dialog form input was wrong.  Phillip traced the issue to covalent and provided this fix.
=> fix(color): set body color based on mode

src/lib/sqle/query.service.ts
- Update result data interface to include numbers
- Exposed new interface
=> fix(query): update result data interface

src/lib/sqle/query.service.ts
Add column types
Pulled from https://docs.teradata.com/reader/~_sY_PYVxZzTnqKq45UXkQ/aq5HXSUqjBoqVmOwlZpKBQ
=> feat(query): add column types

package-lock.json, package.json, src/lib/sqle/query.service.ts, src/lib/theme/theme.service.ts
Adding small fix for Firefox, to prevent cache on back button.
To test:
=> fix: firefox bfCache caching

proxy.conf.js, src/lib/assets/assets.service.ts
Assets container url changed. Update to point to new url.
=> feat(assets-url-change): relocated assets service url
