src/docs-ui/app/main/main.component.ts
src/lib/auth/guards/authentication.guard.ts
src/lib/auth/session/session.service.ts

1. Logout uses redirect instead of api call 
related to https://jira.td.teradata.com/jira/browse/UDAPP-8031

fix(): logout to redirect

---

src/lib/_theming.scss

Panel and dialog should have the same background as mat-card

fix: styles for surface colors & breadcrumbs

---

src/lib/_theming.scss

Small css fix targeting markdown navigator window so it has the same background as our default background on both dark and light mode.

fix: background set to bgc color

---

src/lib/auth/guards/authentication.guard.ts
src/lib/auth/session/session.service.ts

[VUI-385](https://jira.td.teradata.com/jira/browse/VUI-385) - Cached page loads cause /start-login redirect loop
- Added query param with unique value to avoid caching during the SSO process.

fix(sso-loop): added query param to login/logout

---

.travis.yml
scripts/ci/travis-script.sh

Change pipeline to use `npm ci` and also ignore low and moderate errors with npm audit

fix(travis): reduce npm audit error rate

---

src/lib/sqle/query.service.ts

Temporarily add aster and presto systems back due to an interface clash. Will DRY up interfaces in a follow up PR.

fix(query): temp add systems back

---

src/lib/sqle/connection.service.ts

Ran into a case where the ss item got set to empty.

fix(connection-service): handle empty or invalid connection session val

---

package-lock.json
package.json
src/docs-ui/index.html
src/lib/utilities/pre-loader/README.md
src/lib/utilities/pre-loader/index.js
src/lib/utilities/pre-loader/pre-loader.html
src/lib/utilities/pre-loader/pre-loader.scss

- removes need for a placeholder in the index.html, it will just be injected prior to the closing body tag.
- makes fade out transition shorter
- makes spinner smaller.
- added missing sass dart dependency 
- some markup cleanup
Before
After

feat(pre-loader): remove need for placeholder in html && css tweaks

---

src/docs-ui/app/app.module.ts
src/docs-ui/app/app.routes.ts
src/docs-ui/app/demos/demos.component.html
src/docs-ui/app/demos/demos.component.ts
src/docs-ui/app/main/main.component.html
src/docs-ui/app/main/main.component.ts
src/docs-ui/app/mat-components/mat-components.component.ts
src/lib/theme/README.md
src/lib/theme/theme.service.ts

Attempting to address https://github.com/Teradata/vantage-ui-platform/issues/53
- Adds map method
- Might want to get rid of fallback param? Added in case there are more than 2 themes at one point and might not want to specifiy values for all themes?
- Exposes more obs
- Added demos
- Added a README

feat(theme-service): add map method and expose observables

---

src/lib/sqle/connection.service.ts

Expose read-only method, so it can be accessed without having to initiate the service.

fix(connection-service): export read method

---

src/docs-ui/app/mat-components/mat-components.component.html
src/lib/theme/_overrides.scss

Adding mat fab buttons to docs and fixing the border radius bug
from #71

fix(fab-buttons): propagating border radius

---

src/lib/app-switcher/app-switcher.component.ts
src/lib/app-switcher/app-switcher.module.ts
src/lib/app-switcher/index.ts
src/lib/app-switcher/package.json
src/lib/app-switcher/public_api.ts
src/lib/app-switcher/tsconfig.json
src/lib/sqle/package.json
src/lib/tsconfig.spec.json

Adding the app-switcher to the ng packagr build process. and pulling theme file from `@td-vantage/ui-platform/theme` location

feat(app-switcher): adding app switcher to bundle deployment

---

src/lib/sqle/connection.service.ts
src/lib/sqle/credentials-dialog/credentials-dialog.component.spec.ts
src/lib/sqle/query.service.ts

Add a configurable timeout and retry attempts to the connection service that only kicks in if the error is something else than 420 (bad credentials)

feat(sqle): add timeout + retry to conn serv

---

src/lib/sqle/query.service.ts

Add an extra check in case the log mech comes as `logMech` or `log_mech` when trying to use the query service.

fix(sqle): check for log_mech and logMech on system

---

scripts/build-release
src/docs-ui/app/app.component.html
src/docs-ui/app/app.component.ts
src/docs-ui/app/app.module.ts
src/lib/account-profile/_account-profile-theme.scss
src/lib/account-profile/account-profile-menu/account-profile-menu.component.html
src/lib/account-profile/account-profile-menu/account-profile-menu.component.scss
src/lib/account-profile/account-profile-menu/account-profile-menu.component.spec.ts
src/lib/account-profile/account-profile-menu/account-profile-menu.component.ts
src/lib/account-profile/account-profile.component.html
src/lib/account-profile/account-profile.component.spec.ts
src/lib/account-profile/account-profile.component.ts
src/lib/account-profile/account-profile.module.ts
src/lib/account-profile/index.ts
src/lib/account-profile/package.json
src/lib/account-profile/public_api.ts
src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.spec.ts
src/lib/app-switcher/app-switcher.component.spec.ts
src/lib/theme/_overrides.scss

#Description
Adding account profile component. `VantageAccountProfileModule` will include two components
1. `vui-account-profile-menu` - menu content with ng content projectors to for `account-info-list` and `account-actions-list`
2. `vui-account-profile` - icon button and mat menu setup for `vui-account-profile-menu` component
closes #75
```
<vui-account-profile name="donald duck" email="donald.duck@teradata.com">
<ng-container account-info-list>
<mat-list-item></mat-list-item>
</ng-container>
<ng-container account-action-list>
<button mat-list-item></button>
</ng-container>
</vui-account-profile>
```

feat(account-profile): adding account-profile component

---

src/lib/sqle/connection.service.ts

namespace stringify func to avoid clashes

fix(connection-service): namespace stringify func

---

src/docs-ui/app/app.component.ts
src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.html
src/lib/app-switcher/app-switcher-menu/app-switcher-menu.component.scss
src/lib/app-switcher/services/products.service.ts

App switcher modified to have the following behavior:
For Vantage products, the default behavior is to switch apps within the same tab. This can be overridden by specifying newTab: true in the config.
For Other products, the default behavior is to open app in new tab. This can be overridden by specifying newTab: false in the config.

feat(open-apps-new-tab): modify switcher to open new tab

---

src/lib/sqle/query.service.ts

[VUI-856](https://jira.td.teradata.com/jira/browse/VUI-856) - Move create session methods from default database to ui-platform
- update to the createSession() method
- move the payload object and set it as a default param of the method
- created a ISessionPayload interface
Closes [VUI-856](https://jira.td.teradata.com/jira/browse/VUI-856

fix(update): update createsession method with default payload param

---

src/lib/sqle/query.service.ts

QueryBands is an optional property on the ISessionPayload and IQueryPayload objects. The QueryBands property is a map, with reasonable default name/value pairs of ApplicationName, Version and ClientUser. Additional name/value pairs can be specified as appropriate for the application utilizing the API.

Feat/querybands - support querybands on session and query APIs

---

scripts/build-release

On build directory was missing because of a missing script,
this PR adds the missing script
1. Run: ```npm run build:lib```
2. Once done go to path: deploy/ui-platform/theme/long-form-content
3. verify directory contains: _small-scale.scss

build: missing directory
